root = "."
working_dir = "/server"

[build]
cmd = "make build-server"
bin = "bin/server"

include_ext = ["go", "tpl", "tmpl", "html", "css"]
include_file = ["Makefile"]
exclude_dir = ["assets", "tmp", "vendor", "bin", "web"]

[run]
cmd = "make run-server"

[log]
time = true
