root = "."
working_dir = "/server"

[build]
cmd = "go build -o ./bin/server cmd/server/main.go" 
bin = "bin/server"

include_ext = ["go", "tpl", "tmpl", "html", "css"]
include_file = []
exclude_dir = ["assets", "tmp", "vendor", "bin", "web"]

[run]
cmd = "go run cmd/server/main.go"

[log]
time = true
