services:
  db:
    image: postgres:17
    environment: &postgres_env
      POSTGRES_DB: gokapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fullstack

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "migrations"
    environment:
      <<: *postgres_env
      POSTGRES_HOST: db
    networks:
      - fullstack
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["make", "exec-migrations"]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "server"
    environment:
      <<: *postgres_env
      POSTGRES_HOST: db

    ports:
      - "3005:8080"
    networks:
      - fullstack
    volumes:
      - .:/app
    depends_on:
      - migrations

networks:
  fullstack:
    driver: bridge

volumes:
  db_data:
