services:
  db:
    image: postgres:17
    environment: &postgres_env
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fullstack

  migrations:
    working_dir: /server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "migrations"
    environment:
      <<: *postgres_env
      POSTGRES_HOST: db
    networks:
      - fullstack
    volumes:
      - .:/server
    depends_on:
      - db
    command: ["make", "exec-migrations"]

  server:
    working_dir: /server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "server"
    environment:
      <<: *postgres_env
      POSTGRES_HOST: db
      CERT_FILE: ./certs/server.crt
      KEY_FILE: ./certs/server.key
      JWT_SECRET: ${JWT_SECRET}
      PORT: :8443

    ports:
      - "3005:8080"
      - "8443:8443"
    networks:
      - fullstack
    volumes:
      - .:/server
      - ./certs:/server/certs
      - ./web/dist:/server/web/dist # Mount local web/dist for development
    depends_on:
      - migrations

networks:
  fullstack:
    driver: bridge

volumes:
  db_data:
